export const LOGIN_FORM = 'LOGIN_FORM';
export const FETCH_CURRENCIE = 'FETCH_CURRENCIE';
export const SAVE_FORM = 'SAVE_FORM';
export const FETCH_SAVE_EXCHANGE_RATE = 'FETCH_SAVE_EXCHANGE_RATE';
export const DELETE_LIST = 'DELETE_LIST';
